#ifndef _CREOL_CNST_HEADER
#define _CREOL_CNST_HEADER

#define KL_STANDARD_FILE_EXTENSION "kl"

#define KL_STANDARD_COMPILER_NAME "creol"

#define KL_ALTERNATIVE_COMPILER_NAME "kriol"

#endif // _CREOL_CNST_HEADER